apiVersion: v1
kind: Pod
metadata:
  name: nginx-exercicio
spec:
  containers: 
    - name: nginx
      image: nginx:stable
      ports:
        -containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "400Mi"